spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: cheng
    url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  context-path: /sell

#logging:
#  pattern:
#    console: "%d - %msg%n"
#  path: D:/Logs/sell
#  file: D:/Logs/sell/sell.log
#  level:
#    com.imooc.LoggerTest: debug